const fw = {};
import { mainCtrl } from "./mainCtrl/mainCtrl";
import { mapCtrl } from "./mapCtrl/mapCtrl";
import { serverCtrl } from "./serverCtrl/serverCtrl";
import { layerCtrl } from "./layerCtrl/layerCtrl";
import { cameraCtrl } from "./cameraCtrl/cameraCtrl.js";
// import { measureUtils } from "./measureUtils/measureUtils";
// import { geoAnalyser } from "./geometryUtils/geoAnalyser";
// import { geoTransformer } from "./geometryUtils/geoTransformer";
import { geoCreater } from "./geometryUtils/geoCreater.js";
// import { symCreater } from "./symbolUtils/symCreater";
// import { graCreater } from "./graphicUtils/graCreater";
// import { drawCtrl } from "./drawCtrl/drawCtrl";
// import { overviewCtrl } from "./mapCtrl/overviewCtrl";
// import { bookmarkCtrl } from "./cameraCtrl/bookmarkCtrl";
// import { mapLinkage } from "./mapCtrl/mapLinkage";
// import { utilities } from "./mainCtrl/utilities";
import { eventCtrl } from "./mainCtrl/eventCtrl";
// import { queryUtils } from "../sdk/queryUtils/queryUtils.js";
// import { popupCtrl } from "./popupCtrl/popupCtrl.js";
import { esri } from "./mainCtrl/esri";
// import { gpCtrl } from "./gpCtrl/gpCtrl";
import { groundCtrl } from "./mapCtrl/groundCtrl";
import { externalCtrl } from "./mapCtrl/externalCtrl";

fw.mainCtrl = mainCtrl;
fw.mapCtrl = mapCtrl;
fw.serverCtrl = serverCtrl;
fw.layerCtrl = layerCtrl;
fw.cameraCtrl = cameraCtrl;
// window.fw.measureUtils = measureUtils;
// window.fw.geoAnalyser = geoAnalyser;
// window.fw.geoTransformer = geoTransformer;
fw.geoCreater = geoCreater;
// window.fw.symCreater = symCreater;
// window.fw.graCreater = graCreater;
// window.fw.drawCtrl = drawCtrl;
// window.fw.overviewCtrl = overviewCtrl;
// window.fw.bookmarkCtrl = bookmarkCtrl;
// window.fw.mapLinkage = mapLinkage;
// window.fw.utilities = utilities;
fw.eventCtrl = eventCtrl;
// window.fw.queryUtils = queryUtils;
// window.fw.popupCtrl = popupCtrl;
fw.esri = esri;
// window.fw.gpCtrl = gpCtrl;
fw.groundCtrl = groundCtrl;
fw.externalCtrl = externalCtrl;
export { fw };
